python Train_jn_pencil.py --gpuid=0 --r=0.2 --noise_mode="sym"
python Train_jn_pencil.py --gpuid=0 --r=0.5 --noise_mode="sym"
python Train_jn_pencil.py --gpuid=0 --r=0.8 --noise_mode="sym"
python Train_jn_pencil.py --gpuid=0 --r=0.9 --noise_mode="sym"
python Train_jn_pencil.py --gpuid=0 --r=0.4 --noise_mode="asym"