python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=0 --p_threshold=0.4
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=0 --p_threshold=0.6
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=0 --p_threshold=0.8
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=10 --p_threshold=0.4
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=10 --p_threshold=0.6
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=10 --p_threshold=0.8
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=30 --p_threshold=0.4
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=30 --p_threshold=0.6
python Train_jn.py --gpuid=1 --r=0.2 --noise_mode='sym' --lambda_u=30 --p_threshold=0.8

python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=10 --p_threshold=0.4
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=10 --p_threshold=0.6
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=10 --p_threshold=0.8
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=20 --p_threshold=0.4
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=20 --p_threshold=0.6
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=20 --p_threshold=0.8
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=50 --p_threshold=0.4
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=50 --p_threshold=0.6
python Train_jn.py --gpuid=1 --r=0.5 --noise_mode='sym' --lambda_u=50 --p_threshold=0.8