python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=25 --p_threshold=0.4
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=25 --p_threshold=0.6
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=25 --p_threshold=0.8
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=40 --p_threshold=0.4
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=40 --p_threshold=0.6
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=40 --p_threshold=0.8
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=60 --p_threshold=0.4
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=60 --p_threshold=0.6
python Train_jn.py --gpuid=0 --r=0.8 --noise_mode='sym' --lambda_u=60 --p_threshold=0.8

python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=25 --p_threshold=0.4
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=25 --p_threshold=0.6
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=25 --p_threshold=0.8
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=40 --p_threshold=0.4
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=40 --p_threshold=0.6
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=40 --p_threshold=0.8
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=60 --p_threshold=0.4
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=60 --p_threshold=0.6
python Train_jn.py --gpuid=0 --r=0.9 --noise_mode='sym' --lambda_u=60 --p_threshold=0.8