python Train_crwu_cotea.py --gpuid=1 --r=0.2 --noise_mode='sym'
python Train_crwu_cotea.py --gpuid=1 --r=0.5 --noise_mode='sym'
python Train_crwu_cotea.py --gpuid=1 --r=0.8 --noise_mode='sym'
python Train_crwu_cotea.py --gpuid=1 --r=0.9 --noise_mode='sym'
python Train_crwu_cotea.py --gpuid=1 --r=0.2 --noise_mode='asym'
python Train_crwu_cotea.py --gpuid=1 --r=0.5 --noise_mode='asym'
python Train_crwu_cotea.py --gpuid=1 --r=0.8 --noise_mode='asym'
python Train_crwu_cotea.py --gpuid=1 --r=0.9 --noise_mode='asym'